{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghcp-sdk-oai-wrapper.fullname" . }}
  labels:
    {{- include "ghcp-sdk-oai-wrapper.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  {{- if .Values.secrets.apiKey }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
{{- end }}
