package ollama

import (
	"encoding/json"
	"log/slog"
	"net/http"

	wrapper "github.com/olohmann/ghcp-sdk-oai-wrapper/internal/copilot"
)

// Tags returns the handler for GET /api/tags.
func Tags(client *wrapper.Client, logger *slog.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}

		models, err := client.ListModels(r.Context())
		if err != nil {
			logger.Error("failed to list models", "error", err)
			WriteError(w, http.StatusInternalServerError, "failed to list models")
			return
		}

		now := NowRFC3339Milli()
		data := make([]ModelInfo, 0, len(models))
		for _, m := range models {
			data = append(data, ModelInfo{
				Name:       m.ID,
				Model:      m.ID,
				ModifiedAt: now,
				Details:    ModelDetails{},
			})
		}

		WriteJSON(w, http.StatusOK, TagsResponse{Models: data})
	}
}

// Show returns the handler for POST /api/show.
func Show(client *wrapper.Client, logger *slog.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}

		var req ShowRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			WriteError(w, http.StatusBadRequest, "invalid request body: "+err.Error())
			return
		}

		if req.Model == "" {
			WriteError(w, http.StatusBadRequest, "model is required")
			return
		}

		WriteJSON(w, http.StatusOK, ShowResponse{
			Modelfile:  "# Modelfile generated by ghcp-sdk-oai-wrapper\n",
			Parameters: "",
			Template:   "",
			Details:    ModelDetails{},
		})
	}
}
